# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 1

# Personal info
name: Manoj Kesavulu
title: Doctoral Scholar
email: manojpratnas@gmail.com
website: manoj-kesavulu.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: chintu0019
github_username:  chintu0019
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: spongebob.404
linkedin_username: manoj-kesavulu
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Lero, DCU
  icon: fab graduation-cap
  url: https://dcu.lero.ie/team/manojkesavulu/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
- title: Lero | Science Foundation Ireland Research Centre for Software
  icon: fab microscope
  url: https://lero.ie/people/manoj-kesavulu

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/MK.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Manoj and I'm a highly energetic and confident, coding enthusiast always eager to learn new technologies with a master’s degree in Information and Network Security from University of Limerick and pursuing Doctor of Philosophy (PhD) in Usage Analytics for Cloud Applications at Dublin City University.

  I am most skilled in: <mark>Research</mark> <mark>Data analytics</mark> <mark>Programming</mark> and <mark>Gaming</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Industrial collaboration research project with IBM – ‘Usage Analytics – User level SaaS based Usage Analytics’
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started with this two year project in January 2017 as part of the academic-industrial collaboration between Dublin City University and IBM Research Labs. The research investigated user-level usage analysis in the cloud space, focusing on customer usage data mining for cloud on/off-boarding trends, trajectories, risk assessments, tenant/cross-tenant patterns to infer usage confidence. The project determined which features and functions are used, when and how, as this impacts software development costs. The results were two-fold: 1. cost-driven architecture analysis and decision support,2. usage-oriented software improvement and maintenance. The project successfully completed and resulted in an invention.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
