# Site
repository: manoj-kesavulu/manoj-kesavulu.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Manoj Kesavulu
title: Doctoral Scholar
email: manojpratnas@gmail.com
# email_title: Email (Email title override)
phone: "+353894180169"
# phone_title: Phone (Phone title override)
website: https://lero.ie/people/manoj-kesavulu
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: chintu0019
github_username:  chintu0019
stackoverflow_username: "5318554"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: spongebob.404
linkedin_username: manoj-kesavulu
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
orcid_username: 0000-0001-5505-9593

# Additional icon links
additional_links:
- title: Lero, DCU
  icon: fas fa-university
  url: https://dcu.lero.ie/team/manojkesavulu/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/MK.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Manoj and I'm a highly energetic and confident, coding enthusiast always eager to learn new technologies with a master’s degree in Information and Network Security from University of Limerick and pursuing Doctor of Philosophy (PhD) in Usage Analytics for Cloud Applications at Dublin City University.

  I am most skilled in: <mark>Research</mark> <mark>Data analytics</mark> <mark>Programming</mark> and <mark>Gaming :P</mark>
#Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.
#
  #You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports #such as
  #  - Lists
  #  - Tables
  #  - <a href="google.com">Links</a>
  #  - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
# Projects Section
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      # Project 1
      - layout: left
        title: USAGE ANALYTICS
        caption: 2017 - 2019
        link: https://dcu.lero.ie/usage-analytics/
        link_text: Project Homepage
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/chintu0019/Usage-Analytics
        quote: >
          Novel solutions to understand how users use software applications
        description: | # this will include new lines to allow paragraphs
          The project goal is to investigate user-level usage analysis in the cloud space, focusing on customer usage data mining for the cloud on/off-boarding trends, trajectories, risk assessments, tenant/cross-tenant patterns to infer usage confidence. The aim is to determine which features and functions are used, when and how, as this impacts software development costs.
          Developed an analytics approach for understanding end-users’ behavioral changes while interacting with the applications by analysing the usage data generated by the applications and the cloud systems hosting the applications.

          <mark>Python</mark> <mark>IBM Watson Workspace</mark> <mark>Data Analytics</mark> <mark>Flask</mark> <mark>Odoo</mark> <mark>Log management</mark> <mark>Python Dash</mark> <mark>Plotly</mark> <mark>Visual Studio Code</mark> <mark>Git</mark>
      # Project 2
      - layout: left
        title: Adaptive Security Control Demonstrator App
        caption: 2016 - 2017
        link: https://drive.google.com/file/d/0B3qnAsHlYypGX1RodmM3SnFaWmM/view
        link_text: Demonstration Video
        quote: >
          Physical Location and Context-based Authentication Mechanism
        description: | # this will include new lines to allow paragraphs
          The app collect user context information such as Physical location, Network type, device type. These information will be sent to Adaptation Manager which analyses these context information and decides appropriate security control (Authentication mechanism) using which user authenticates using the app to connect to the cloud built using OpenStack. Supports in-app fingerprint authentication.
          
          <mark>Android</mark> <mark>Java</mark> <mark>OpenStack</mark> <mark>Authentication</mark> <mark>Gradle build</mark> <mark>Linux</mark>
      # Project 3
      - layout: left
        title: Intrusion Detection System for Cloud to Detect and Analyse Live Backdoor Attacks
        caption: "2015"
        link: https://drive.google.com/file/d/0B3qnAsHlYypGYnRkMFNmLVpCUzQ/view
        link_text: Dissertation Report
        quote: >
          Created a backdoor virus and developed a novel Intrusion Detection System
        description: | # this will include new lines to allow paragraphs
          Private cloud environment is built using Eucalyptus cloud software. The attack performed is the backdoor root access to a terminal using Metasploit tool. Upon gaining access, forensic analysis (live network packet logging) is performed using various tools provided to the Linux systems and successfully determine a way to detect this particular attack and collect the evidence.

          <mark>Penetration Testing</mark> <mark>Metasploit</mark> <mark>Backdoor Exploit development</mark> <mark>Nessus</mark> <mark>tcpdump</mark> <mark>Nmap</mark> <mark>Data Forensics</mark> <mark>Intrusion Detection and Prevention Mechanisms</mark> 
      # Project 4
      - layout: left
        title: Data Forensics Tool to Evaluate MBR Record
        caption: "2014 - 2015"
        #link: https://drive.google.com/file/d/0B3qnAsHlYypGYnRkMFNmLVpCUzQ/view
        #link_text: Dissertation Report
        quote: >
          Data Forensics Tool to Verify Evidence and Recover Lost Data
        description: | # this will include new lines to allow paragraphs
          A C++ based tool for extracting information for examination to be used as evidence or even to recover lost data. In digital forensic analysis, Master Boot Record is captured to extract the required information of the hard disk to support the investigation process. 

          <mark>C++</mark> <mark>Data Forensics</mark> <mark>MBR</mark> <mark>Linux Scripting</mark>  
      # Project 5
      - layout: left
        title: Card Game Simulator
        caption: "2014 - 2015"
        #link: https://drive.google.com/file/d/0B3qnAsHlYypGYnRkMFNmLVpCUzQ/view
        #link_text: Dissertation Report
        quote: >
          A simple and cool card game
        description: | # this will include new lines to allow paragraphs
          Developed a Java tool to simulate the Rummy card game with dynamic number of player selection

          <mark>Java</mark> <mark>Statistical Analysis</mark> <mark>Linux Scripting</mark>
      # Project 6
      - layout: left
        title: Card Game Simulator
        caption: "2012 - 2013"
        #link: https://drive.google.com/file/d/0B3qnAsHlYypGYnRkMFNmLVpCUzQ/view
        #link_text: Dissertation Report
        quote: >
          A simple and cool card game
        description: | # this will include new lines to allow paragraphs
          Built a basic private Cloud system using OpenStack and developed a C++ tool for analysis of various scheduling algorithms (FIFO, Round-robin scheduling, LIFO, Preemptive scheduling) for the purpose of determining performance variations between the algorithms. (Part of my bachelor’s final year project to decide which algorithm would suit best for a private cloud environment)

          <mark>C++</mark> <mark>OpenStack</mark> <mark>FIFO</mark> <mark>Round-Robin</mark> <mark>Linux</mark>

  # Experience Section
  - title: Experience
    layout: list
    content:
      # Experience 1
      - layout: left
        title: IBM Research Labs
        sub_title: Research Intern
        caption: "2017 - 2019"
        additional_links:
          - title:  IBM, Dublin, Ireland
            icon: far fa-building
            url: https://www.research.ibm.com/labs/ireland/
        quote: >
          Usage Analytics Invention 
        description: | # this will include new lines to allow paragraphs
          - Designed an analytics approach and developed a prototype for understanding end-users’ behavioural changes while interacting with the applications by analysing the usage data generated by the applications and the cloud systems hosting the applications
          - Developed a web mining tool to extract usage data from IBM Watson Workspace application
          - Initial generic refactoring methodology is proposed (Kesavulu et al. 2017)
          - Issues related to architectural decisions reducing performance and scalability in cloud environments are identified from the literature (Kesavulu et al. 2016)
          - Designed usage data extraction framework adhering to the identified usage data criteria (Kesavulu et al. 2017)
          - Identified the usage data sources in a cloud environment, specifically with Watson Workspace platform
          - Review of the state-of-the-art cloud monitoring solutions (Kesavulu et al. 2018)
          - Developed the Feature-action map for Watson Workspace
          - Development of interactive visualization dashboard with python flask, google collab
          - Application of the UA model to Watson Workspace; designed and performed the experiment to extract the usage data and evaluate the approach 
          - Invention disclosure at DCU and IBM

          <mark>Python</mark> <mark>Linux</mark> <mark>shell scripting</mark> <mark>Flask</mark> <mark>Pandas</mark> <mark>Statistical Mathematics</mark> <mark>Web Mining</mark> <mark>Data Processing</mark> <mark>Data Analytics</mark> <mark>ETL</mark> <mark>NewRelic</mark> <mark>GraphQL</mark> <mark>ElasticSearch</mark> <mark>plotly</mark>
      # Experience 2
      - layout: left
        title: Lero, University of Limerick
        sub_title: Research Assistant
        caption: "2015 - 2016"
        additional_links:
          - title:  Lero, Limerick, Ireland
            icon: far fa-building
            url: https://lero.ie
        quote: >
          Context-based Authentication Proof-of-concept
        description: | # this will include new lines to allow paragraphs
          - Built a private cloud and developed an adaptive security demonstrator using android as security endpoint for the cloud
          - Analyzed IaaS cloud security framework 
          - Context information such as device type, physical location & network type using the android app built as a data mining tool
          - Developed python web service acting as an adaptation manager which decides appropriate authentication mechanism depending on the context information
          - Developed in-app fingerprint authentication for android app
          - Scientific and critical reviewing of research papers
          - Developed research skills, teamwork with a team of diverse skills, project management and technical skills

          <mark>Linux</mark> <mark>Java</mark> <mark>Linux Containers</mark> <mark>Python</mark> <mark>Bash Scripting</mark> <mark>Git</mark> <mark>OpenStack</mark> <mark>Android Development</mark>
      # Experience 3
      - layout: left
        title: Freelance
        sub_title: Web Designer and Developer
        caption: "2013 - 2014"
        quote: >
           Development of Web Applications
        description: | # this will include new lines to allow paragraphs
          - Designed dynamic web applications, development and maintenance of websites for various start-ups and various projects from small companies 
          - Quantitative and Qualitative analysis of websites
          - Regression, unit and integration testing of java applications using JUnit
          - Developed the ability to work alone, time management, business, project management, customer interaction, technical skills

          <mark>HTML</mark> <mark>CSS</mark> <mark>PHP</mark> <mark>Java</mark> <mark>Java SE</mark> <mark>JUnit</mark> <mark>JavaScript</mark> <mark>AngularJS</mark> <mark>MySQL</mark>

  # Education Section        
  - title: Education
    layout: list
    content:
      # Education 1
      - layout: top-left
        title: Dublin City University (DCU)
        sub_title: Doctor of Philosophy (PhD)
        caption: 2016 - Present
        quote: >
          Software Usage Analytics
        description: | # this will include new lines to allow paragraphs
          Thesis: ’Usage Analytics - Understanding Usage Behavior of the Software Users’

          <mark>Python</mark> <mark>Linux</mark> <mark>shell scripting</mark> <mark>Flask</mark> <mark>Pandas</mark> <mark>Web Mining</mark> <mark>Data Processing</mark> <mark>Data Analytics</mark> <mark>ETL</mark> <mark>NewRelic</mark> <mark>GraphQL</mark> <mark>ElasticSearch</mark> <mark>plotly</mark> <mark>Latex</mark> <mark>Overleaf</mark> 
      # Education 2
      - layout: top-left
        title: University of Limerick (UL)
        sub_title: Master of Engineering 
        caption: 2014 - 2015
        quote: >
          Information and Network Security
        description: | # this will include new lines to allow paragraphs
          Thesis: ’A Cloud Computing Digital Forensics Method Based on Detecting and Analyzing Live Backdoor Attacks’
                
          <mark>Penetration Testing</mark> <mark>Metasploit</mark> <mark>Backdoor Exploit development</mark> <mark>Nessus</mark> <mark>tcpdump</mark> <mark>Nmap</mark> <mark>Data Forensics</mark> <mark>Intrusion Detection System</mark>
      # Education 3
      - layout: top-left
        title: Visveswaraya Technological university (VTU)
        sub_title: Bachelor of Engineering
        caption: 2009 - 2013
        quote: >
          Computer Science and Engineering
        description: | # this will include new lines to allow paragraphs
          Thesis: ’Optimization of Data Processing in Private Cloud’

  # Awards Section
  - title: Awards
    layout: list
    content: 
      # Award 1
      - layout: top
        title: Project of the Year - Tech Excellence Awards
        sub_title: Techcentral.ie
        caption: "2019"
        description: Finalist for the Project of the Year at the Tech Excellence Awards 2019 held at CIty West Hotel, Dublin, Ireland for the project "Usage Analytics"
      # Award 2
      - layout: top-left
        title: Outstanding Academic Achievement Award - Industry Awards
        sub_title: Technology Ireland and IBEC
        caption: "2018"
        description: Runner-up Outstanding Academic Achievement Award at the Industry Awards 2018
      # Award 3
      - layout: top-left
        title: DCU President’s Awards for Commercialisation
        sub_title: Dublin City University
        caption: "2017"
        description: DCU President’s Awards for Commercialisation for the research collaboration project with IBM Research Labs
      # Award 4  
      - layout: top-left
        title: Best Science Project
        sub_title: Southern India Science Fair
        caption: "2006"
        description: Won the 2nd prize at the best science project award for the project "Bio-Mathematics" presented by Directorate of School Education Govt. of Pondicherry and Visveswaraya Industrial & Technological Museum, Bangalore, India
      #Award 5  
      - layout: top-left
        title: Best Science Project
        sub_title: State-level Science Fair
        caption: "2006"
        description: Won the best science project award for the project "Bio-Mathematics" presented by Sarvajanika Shikshana Ilake, Govt. of Karnataka, India
   

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
